---
title: "daily27-28"
format: html
---

#### Define River Object

We we extract a river profile from the Poudre River in Fort Collins, CO.

1.  To do use the code from lecture to extract all `waterways` from OpenStreetMap for the Bounding Box of Fort Collins, CO.

2.  Filter the `osm_lines` object to only include the `Cache la Poudre River` and merge the lines into a single line object with `st_union()`. Be sure to convert the object to a `sf` object with `st_as_sf()` when done.

3.  Use `st_length()` to compute the length of the river for future calculations.

4.  Use `st_cast()` to convert the river object to a `POINT` object and save it as `poudre_pts` for latter extraction tasks

#### Define DEM Object

5.  Use the `rast()` function to read in the DEM file from the `lynker-spatial` S3 bucket shared in last assignment. Be sure to use the vsis3 prefix!

#### Extract River Profile

6.  Use the `extract()` function to extract the elevation values from the DEM at the points along the river.

7.  Use `bind_cols()` to combine the spatial river points with the extracted elevation values.

8.  Use `mutate()` to add a new column called `ID` that is a sequence from 1 to the number of points in the river (`n()`).

#### Compute Sinuosity

9.  Use the `st_distance()` function to compute the straight line distance between the first and last points in the river.

10. Divide the length of the full river (step 3) by this straight line distance to get the sinuosity. Report the value and what it means. Does this value make sense with respect to the complete Poudre River?

#### Compute Slope

11. The slope of a river is the change in elevation between the inlet and outlet divided by the length of the river. Compute this value and report it. Remember the units of the elevation (cm) and of your length!

#### Map Profile: 2 ways

Last, we want to visualize the river profile.

12. Use `ggplot()` to create a line plot of the elevation values along the river. Be sure to use the `ID` column as the x-axis and the `dem` column as the y-axis. Add nice lables and themese to your chart.

13. Use `ggplot()` to plot the spatial mpa of the river profile. Use the `geom_sf()` function to plot the river and color it by elevation. Be sure to use a nice color scale and theme.

Convert all of this into a Quarto document and submit a link to the deployed document on GitHub to the Canvas.

Congrats!
